project:
  output-dir: docs
  type: book

book:
  site-url: "https://jmbuhr.de/dataadvanced/"
  title: "Advanced Data Analysis with R"
  subtitle: "and python!"
  author: "Jannik Buhr"
  description-meta: "This is where you will find all the resources for the course Advanced Data Analysis with R"
  date: today
  date-meta: today
  image: cover.png
  favicon: "favicon.png"
  page-navigation: true
  search: true
  repo-url: https://github.com/jmbuhr/dataadvanced
  repo-actions: [issue, source]
  # downloads: [pdf, epub]
  # sharing: [twitter]
  open-graph: true
  # twitter-card:
  #   creator: "@jannikbuhr"
  chapters:
    - index.qmd
    - ./01-workflow.qmd
    - ./02-communication.qmd
    - ./03-projects.qmd
    - ./04-machine-learning.qmd
    - ./05-omics.qmd
  appendices:
    - ./references.qmd
    - ./resources.qmd

execute:
  cache: true
  echo: true
  warning: false
  message: false
  freeze: false

knitr:
  opts_chunk:
    comment: ""
    out.width: "100%"
    echo: TRUE
    paged.print: TRUE


bibliography: references.bib
citation:
  license: "CC BY"
  type: book
  author: Jannik Buhr
  collection-title: Introduction to Data Analysis with R
  issued: 2022-05-17
  abstract: |
    An introductory course to data analysis with R.


format:
  html:
    theme:
      light: [default, theme.scss]
      dark: [default, darkly, theme.scss]
    mainfont: Roboto
    monofont: Fira Mono
    css: ./style.css
    number-sections: true 
    code-link: true
    reference-links: true
    reference-location: margin


